hpcc-systems/hpcc-js-wasm

package-lock.json
package.json

chore(build): Bump versions to patch latest security issues

---

package-lock.json
package.json

chore(security): Bump library versions

---

.dockerignore
.travis.yml
README.md
package.json
scripts/cpp-install-prerequisites.sh
test/ubuntu-dev.dockerfile

Remove prerequisites script and add manual steps to README.md
Fixes #15

chore(build):  Add dockerfile for testing clean install

---

.github/workflows/npmPublish.yml
.github/workflows/testPullRequest.yml

chode(build): Fix GitHub action scripts

---

.github/workflows/npmPublish.yml

chore(build): Add scope for automatic publish

---

.github/workflows/npmPublish.yml
.github/workflows/testPullRequest.yml
scripts/cpp-install-graphviz.sh

chore(graphviz): Bump Graphviz version to 2.42.4

---

README.md
cpp/graphviz/graphvizlib/main.cpp
cpp/graphviz/graphvizlib/main.hpp
cpp/graphviz/graphvizlib/main.idl
src/graphviz.ts
test/graphviz.spec.js

feat:  Add support for yInvert and nop

---

README.md
index.html
scripts/cpp-install-graphviz.sh

feat(graphviz):  Bump version to 2.44.1

---

.github/workflows/npmPublish.yml
package.json
utils/purge-jsdelivr.js

chore(build):  Script to purge jsdelivr cache

---

README.md
src/__tests__/graphviz.ts
src/graphviz.ts

feat(sfdp):  Add SFDP support

---

README.md
index.html

chore(testing):  Add github demo

---

README.md
scripts/cpp-install-graphviz.sh

feat(graphviz):  Bump version to 2.47.0

---

scripts/cpp-install-graphviz.sh

feat(graphviz):  Bump version to 2.47.1

---

README.md
scripts/cpp-install-graphviz.sh

chore(graphviz):  Bump version to 2.7.2

---

cpp/graphviz/config.h
cpp/graphviz/lib/gvc/CMakeLists.txt
scripts/cpp-install-graphviz.sh

chore(graphviz):  Simplify Graphviz install

---

package.json
rollup.config.js

feat:  Include individual bundles

---

cpp/graphviz/CMakeLists.txt
package-lock.json
package.json
src/__tests__/dot001.ts
src/__tests__/dot002.ts
src/__tests__/graphviz.ts

fix(graphviz): Add missing options (and defaults)

---

.vscode/launch.json
README.md
bin/cli.js
index.html
package-lock.json
package.json
rollup.config.js

feat:  Add Command Line Interface

---

package-lock.json
package.json
src/graphviz.ts

chore(security):  Bump versions

---

.github/workflows/npmPublish.yml

fix(publish): Auto releasing fails in GH Action

---

src/expat.ts
src/graphviz.ts
src/util.ts

fix:  wasmBinary should be an ArrayBuffer

---

.github/workflows/testPullRequest.yml
karma.conf.js
rollup.config.mjs
src/__tests__/base91.ts
src/__tests__/worker.ts
src/fetch-browser.ts

Fix worker issue (missing globalThis)

fix:  Add web worker unit test

---

.gitignore
CMakeLists.txt
index.html
package.json
rollup-sfx.config.mjs
rollup.config.mjs
src/__bin__/sfx-wasm.mts
src/extract.ts
src/graphviz.ts
src/index-common.ts
src/sfx-graphviz.ts

feat:  Add self extracting wasm "sfx-graphviz"

---

.github/workflows/testPullRequest.yml
cpp/graphviz/CMakeLists.txt
cpp/graphviz/graphvizlib/main.cpp
cpp/graphviz/lib/cgraph/CMakeLists.txt
cpp/graphviz/lib/neatogen/CMakeLists.txt
cpp/graphviz/lib/ortho/CMakeLists.txt
cpp/graphviz/lib/sfdpgen/CMakeLists.txt
cpp/graphviz/lib/vpsc/CMakeLists.txt
cpp/graphviz/plugin/neato_layout/CMakeLists.txt
package.json
scripts/cpp-install-graphviz.sh

Rollback other 16.x changes
Signed-off-by: GordonSmith <GordonJSmith@gmail.com>

chore:  Bump Graphviz Ver

---

README.md
scripts/cpp-install-emsdk.sh
scripts/cpp-install-graphviz.sh

GraphViz:  7.0.4
Emsdk:  3.1.27
Signed-off-by: GordonSmith <GordonJSmith@gmail.com>

feat:  Bump versions

---

.vscode/launch.json
hw-base91.html
hw-graphviz.html
hw-zstd.html
index.html

fix:  Update test/demo pages to work with es6

---

hw-base91.html
hw-graphviz.html
hw-zstd.html

fix:  Convert local import to be dynamic

---

src-cpp/graphviz/main.cpp
src-cpp/graphviz/main.hpp
src-cpp/graphviz/main.idl
src-ts/__tests__/graphviz.ts
src-ts/graphviz.ts

fixes https://github.com/hpcc-systems/hpcc-js-wasm/issues/149

feat:  Add unflatten method

---

docs/graphviz-cli.md
src-ts/__bin__/dot-wasm.ts
src-ts/__tests__/graphviz.ts
src-ts/graphviz.ts

feat:  Add nop and nop2 layout options

---

.github/workflows/release-please.yml
.github/workflows/test-and-publish.yml
package-lock.json
package.json
packages/base91/package.json
packages/duckdb/package.json
packages/duckdb/test/duckdb.ts
packages/expat/package.json
packages/graphviz-cli/package.json
packages/graphviz/package.json
packages/wasm/package.json
packages/zstd/package.json

Only perform linto on CI (drop lint-skypack)
Add publish support to release-please
Bump versions

fix:  Clean up publish action

---

packages/wasm/esbuild.mjs

GH-257 Add missing DuckDB to wasm package
